# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Flutter Source

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ 'self-hosted', 'linux', 'x64' ]
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Installing dependences
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Analyze project source
        # run: flutter analyze > flutter_analyze_report.txt

      # - uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.1.0'
      #     bundler-cache: true

      # - uses: actions/cache@v1
      #   with:
      #     path: vendor/bundle
      #     key: ${{ runner.os }}-gems-${{ hashFiles('.github/Gemfile') }} # change your gemfile path
      #     restore-keys: |
      #       ${{ runner.os }}-gems-

      # - name: Run Danger
      #   uses: MeilCli/danger-action@v5
      #   with:
      #     plugins_file: '.github/Gemfile'
      #     install_path: 'vendor/bundle'
      #     danger_file: '.github/Dangerfile'
      #     danger_id: 'danger-pr'
      #   env:
      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      # Build Android apps.
#      - name: Build Android (aab file).
#        run: flutter build appbundle

#      # Build iOS apps.
#      - name: Build iOS.
#        run: flutter build ios